import { ref } from 'vue'
import type { ProjectionRow } from '@/core/projection'
import type { CoastFireInputs, CoastFireResult } from '@/types'

// ── Pure functions (exported for testing) ─────────────────────────────────

const CSV_HEADER = 'Year,Age,SIPP (£),Other Investments (£),Total Portfolio (£),Coast FIRE Reached,Milestone'

/**
 * Converts a projection row array to a CSV string.
 * Columns: Year, Age, SIPP, Other, Total, CoastReached, Milestone
 */
export function buildCsvContent(rows: ProjectionRow[]): string {
  const coastIndex = rows.findIndex(r => r.coastReached)

  const lines = rows.map((row, i) => {
    const milestones: string[] = []
    if (i === coastIndex)       milestones.push('Coast FIRE Reached')
    if (row.isRetirementYear)   milestones.push('Retirement')
    if (row.isStatePensionYear) milestones.push('State Pension')

    return [
      row.year,
      row.age,
      Math.round(row.sippValue),
      Math.round(row.otherValue),
      Math.round(row.totalValue),
      row.coastReached ? 'Yes' : 'No',
      milestones.join(' / '),
    ].join(',')
  })

  return [CSV_HEADER, ...lines].join('\n')
}

const gbp = (v: number) =>
  new Intl.NumberFormat('en-GB', {
    style: 'currency',
    currency: 'GBP',
    maximumFractionDigits: 0,
  }).format(v)

/**
 * Builds a plain-text summary of the key results for clipboard copy.
 */
export function buildSummaryText(
  results: CoastFireResult,
  inputs: CoastFireInputs,
): string {
  const lines: string[] = [
    'Coast FIRE Summary',
    '==================',
    `FIRE number:         ${gbp(results.fireNumber)}`,
    `Coast FIRE number:   ${gbp(results.coastFireNumber)}`,
    `Current total:       ${gbp(results.currentTotal)}`,
    '',
  ]

  if (results.hasCoasted) {
    const surplus = results.currentTotal - results.coastFireNumber
    lines.push('Status:              Already coasted!')
    lines.push(`Surplus:             ${gbp(surplus)}`)
  } else {
    lines.push(`Gap to coast:        ${gbp(results.amountToCoast)}`)
    if (results.projectedCoastAge !== null) {
      lines.push(`Projected coast:     Age ${results.projectedCoastAge} (${results.projectedCoastYear})`)
    } else {
      lines.push('Projected coast:     Not reached within projection')
    }
  }

  lines.push('')
  lines.push(`Retirement age:      ${inputs.retirementAge}`)
  lines.push(`Annual expenses:     ${gbp(inputs.annualRetirementExpenses)}/year`)
  lines.push(`Real return rate:    ${inputs.realAnnualReturnRate}%`)
  lines.push(`Safe withdrawal:     ${inputs.safeWithdrawalRate}%`)
  lines.push('')
  lines.push('Generated by Coast FIRE Calculator')

  return lines.join('\n')
}

// ── Composable ─────────────────────────────────────────────────────────────

export function useExport() {
  const copied = ref(false)

  function downloadCsv(rows: ProjectionRow[], filename = 'coast-fire-projection.csv') {
    const content = buildCsvContent(rows)
    const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  async function copyToClipboard(results: CoastFireResult, inputs: CoastFireInputs) {
    const text = buildSummaryText(results, inputs)
    await navigator.clipboard.writeText(text)
    copied.value = true
    setTimeout(() => { copied.value = false }, 2000)
  }

  return { downloadCsv, copyToClipboard, copied }
}
